### PR TITLE
Feature/manage products

### LINKED ISSUE #8: Develop product management section

### LINKED ISSUE #15: Implement image upload and delete

### LINKED ISSUE #25: Implement product filtering

### LINKED ISSUE #30: Prevent Categories from being deleted if there are associated products

### PR DESCRIPTION
**Pull request by methminug**
Fixes #8 
Fixes #15 
Fixes #25 
Fixes #30

### CODE REVIEW

**Review by Akalanka47000 — APPROVED** [review]

**Comment by Shehanka** [comment]
@Akalanka47000 why CI is faling?

**Comment by Akalanka47000** [comment]
> @Akalanka47000 why CI is faling?

Fork PRs aren't able to read the repo secrets for some reason. It's failing due to not being able to read the jks file

**Comment by Shehanka** [comment]
> > @Akalanka47000 why CI is faling?
> 
> Fork PRs aren't able to read the repo secrets for some reason. It's failing due to not being able to read the jks file

let's have a call and discuss

**Comment by Akalanka47000** [comment]
> > > @Akalanka47000 why CI is faling?
> > 
> > 
> > Fork PRs aren't able to read the repo secrets for some reason. It's failing due to not being able to read the jks file
> 
> let's have a call and discuss

Sure, let me know a time slot when you'll be free

**Pull request merged**
